language: cpp
      
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: windows
    - os: windows
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  
notifications:
  email: false