language: cpp
      
matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
      compiler: gcc-8
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-8
      compiler: clang-8
      env:
        - CC=clang-8
        - CXX=clang++-8
    - os: windows
    - os: windows
      compiler: clang

install:
  - pip install conan
  - conan user
script:
  - conan install .
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  
notifications:
  email: false