language: cpp

matrix:
  include:
    - os: linux
      name: 'Linux GCC'
      python: 3.7
      dist: focal
      addons:
        apt:
          packages:
            - gcc-10
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10
      compiler: gcc-10
    - os: linux
      name: 'Linux Clang-10'
      python: 3.7
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-10 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      compiler: clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10
    - os: windows
      name: 'Windows MSVC'
      env:
        - COMPILER="MSVC"
    - os: windows
      name: 'Windows Clang'
      compiler: clang
      env:
        - CMAKE_OPTIONS="-TClangCL -DWARNINGS_AS_ERRORS=0"
        - COMPILER=clang
    - os: linux
      name: 'Cppcheck'
      python: 3.7
      dist: focal
      addons:
        apt:
          packages:
            - gcc-10
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10
        - CMAKE_OPTIONS="-DENABLE_CPPCHECK=ON"
      compiler: gcc-10
      before_install:
        - travis/before_install/install_cppcheck.sh
    - os: linux
      name: 'Clang-tidy'
      python: 3.7
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-10 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - clang-tidy-10
      compiler: clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10
        - CMAKE_OPTIONS="-DENABLE_CLANG_TIDY=ON"

# these scripts must run in the current shell, as they might modify some environment variables
before_install:
  - . travis/before_install/$TRAVIS_OS_NAME.sh
install:
  - . travis/install/$TRAVIS_OS_NAME.sh
script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -j 6
  - ctest . -C Release

notifications:
  email: false