language: cpp
      
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8.0 && CXX=g++-8.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-buster-8
            - sourceline: 'http://apt.llvm.org/buster/ llvm-toolchain-buster-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - os: windows
    - os: windows
      compiler: clang

before_install:
- eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  
notifications:
  email: false