language: cpp

matrix:
  include:
    - os: linux
      name: 'Linux GCC'
      python: 3.7
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
      compiler: gcc-8
    - os: linux
      name: 'Linux Clang-8'
      python: 3.7
      dist: bionic
      addons:
        apt:
          packages:
            - clang-8
      compiler: clang-8
      env:
        - CC=clang-8
        - CXX=clang++-8
    - os: windows
      name: 'Windows MSVC'
      before_install:
        - choco install python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
    - os: windows
      name: 'Windows Clang'
      compiler: clang
      before_install:
        - choco install python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
        - CMAKE_OPTIONS="-TClangCL"


install:
  - pip install --user conan
  - conan user
  - conan profile new default --detect 
script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. $CMAKE_OPTIONS
  - cmake --build .
  
notifications:
  email: false