language: cpp

cache:
  pip: true
  cargo: true
  directories:
    - $HOME/.conan

matrix:
  include:
    - os: linux
      name: 'Linux GCC'
      python: 3.7
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
          packages:
            - gcc-10
            - g++-10
            - cmake
            - libgtk2.0-dev
      env:
        - CC=gcc-10
        - CXX=g++-10
        - RUN_TESTS=true
      compiler: gcc-10
    - os: linux
      name: 'Linux Clang-10'
      python: 3.7
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-10 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
          packages:
            - clang-10
            - cmake
            - libgtk2.0-dev
      compiler: clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10
        - RUN_TESTS=true
    - os: windows
      name: 'Windows MSVC'
      env:
        - COMPILER="MSVC"
        - RUN_TESTS=true
    - os: windows
      name: 'Windows Clang'
      compiler: clang
      env:
        - CMAKE_OPTIONS="-TClangCL -DWARNINGS_AS_ERRORS=0"
        - COMPILER=clang
        - RUN_TESTS=true
    - os: linux
      name: 'Cppcheck'
      python: 3.7
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
          packages:
            - gcc-10
            - g++-10
            - cmake
            - libgtk2.0-dev
      env:
        - CC=gcc-10
        - CXX=g++-10
        - CMAKE_OPTIONS="-DENABLE_CPPCHECK=ON"
        - RUN_TESTS=false
        - INSTALL_CPPCHECK=true
      compiler: gcc-10
      before_install:
        - travis/before_install/install_cppcheck.sh
    - os: linux
      name: 'Clang-tidy'
      python: 3.7
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-10 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
          packages:
            - clang-10
            - clang-tidy-10
            - cmake
            - libgtk2.0-dev
      compiler: clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10
        - CMAKE_OPTIONS="-DENABLE_CLANG_TIDY=ON"
        - RUN_TESTS=false

# these scripts must run in the current shell, as they might modify some environment variables
before_install:
  - . travis/before_install/$TRAVIS_OS_NAME.sh
install:
  - . travis/install/$TRAVIS_OS_NAME.sh
script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -j 6
  - if [ "$RUN_TESTS" = true ] ; then ctest . -C Release --jobs 4 ; fi

notifications:
  email: false