language: cpp

matrix:
  include:
    - os: linux
      name: 'Linux GCC'
      python: 3.7
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
      compiler: gcc-8
    - os: linux
      name: 'Linux Clang-9'
      python: 3.7
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      compiler: clang-9
      env:
        - CC=clang-9
        - CXX=clang++-9
    - os: windows
      name: 'Windows MSVC'
      env:
        - COMPILER="MSVC"
    - os: windows
      name: 'Windows Clang'
      compiler: clang
      env:
        - CMAKE_OPTIONS="-TClangCL -DWARNINGS_AS_ERRORS=0"
        - COMPILER=clang
    - os: linux
      name: 'Cppcheck'
      python: 3.7
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - CMAKE_OPTIONS="-DENABLE_CPPCHECK=ON"
      compiler: gcc-8
      before_install:
        - travis/before_install/install_cppcheck.sh
    - os: linux
      name: 'Clang-tidy'
      python: 3.7
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - clang-tidy-9
      compiler: clang-9
      env:
        - CC=clang-9
        - CXX=clang++-9
        - CMAKE_OPTIONS="-DENABLE_CLANG_TIDY=ON"

# these scripts must run in the current shell, as they might modify some environment variables
before_install:
  - . travis/before_install/$TRAVIS_OS_NAME.sh
install:
  - . travis/install/$TRAVIS_OS_NAME.sh
script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -j 6
  - ctest . -C Release
  
notifications:
  email: false