name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    env:
      COMPILER: MSVC
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          packages: conan
      - run: ./.github/workflows/scripts/install/windows.sh
      - run: |
          mkdir build
          cd build
          cmake .. $CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -j 6
          ctest . -C Release
