name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            compiler: MSVC
            script: windows
          - os: windows-2019
            compiler: clang
            script: windows
            cmake-options: "-TClangCL -DWARNINGS_AS_ERRORS=0"
          - os: ubuntu-20.04
            compiler: gcc-10
            cc: gcc-10
            ccx: g++-10
            script: linux
          - os: ubuntu-20.04
            compiler: clang-10
            cc: clang-10
            ccx: clang++-10
            script: linux
          - os: ubuntu-20.04
            compiler: clang-10
            cc: clang-10
            ccx: clang++-10
            script: linux
            cmake-options: "-DENABLE_CLANG_TIDY=ON"
            install-packages: "clang-tidy-10"
    env:
      COMPILER: ${{ matrix.compiler }}
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.ccx }}
      CMAKE_OPTIONS: ${{ matrix.cmake-options }}
      INSTALL_PACKAGES: ${{ matrix.install-packages }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          packages: conan
      - run: ./.github/workflows/scripts/install/${{ matrix.script }}.sh
        shell: bash
      - run: |
          mkdir build
          cd build
          cmake .. $CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -j 6
          ctest . -C Release
        shell: bash
