name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    env:
      COMPILER: MSVC
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/scripts/install/windows.sh
